version: 2
jobs:
  build:
    machine:
      enabled: true
    working_directory: ~/repo

    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-

    - run: npm install

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    - run: npm run build

    - run: npm install -g cfn-create-or-update

    - run: cfn-create-or-update --stack-name kotlin-course-client --template-body file://deployment.yml --region eu-west-1 --wait

    - run: aws s3 sync ./build s3://kloudformation-web/